### ISSUE TITLE
Error stacktrace when no modem in system

### ISSUE THREAD

**Issue by vladkozlov69** [vladkozlov69/homeassistant_modem#1]
>async_setup_entry => {}
{}
2020-07-22 11:56:25 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.gsm_modem fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/helpers/entity.py", line 465, in async_device_update
    await self.hass.async_add_executor_job(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.homeassistant/custom_components/mm_modem/binary_sensor.py", line 87, in update
    self._signal_strength = gateway.get_signal_strength()
  File "/root/.homeassistant/custom_components/mm_modem/gateway.py", line 118, in get_signal_strength
    modem = self.get_mm_modem()
  File "/root/.homeassistant/custom_components/mm_modem/gateway.py", line 52, in get_mm_modem
    mm_object = self.get_mm_object()
  File "/root/.homeassistant/custom_components/mm_modem/gateway.py", line 47, in get_mm_object
    return manager.get_objects()[0]
IndexError: list index out of range

**Comment by vladkozlov69** [comment]
Fixed
